ielis/hpo-toolkit

- pyproject.toml
- recipe/meta.yaml
We can support Python 3.6 and better as there is currently no functionality that would prevent us doing so.
> Support Python 3.6

- notebooks/Tutorial.ipynb
- src/hpotk/graph/_api.py
- src/hpotk/graph/test__api.py
Add methods for testing if a pair of `TermId`s are parents, ancestors, descendants, or children to the `OntologyGraph`.
> Add methods for testing ancestor/descendant relationships to `OntologyGraph`

- notebooks/Tutorial.ipynb
- src/hpotk/annotations/__init__.py
- src/hpotk/annotations/_api.py
- src/hpotk/annotations/_base.py
- src/hpotk/annotations/_simple.py
- src/hpotk/annotations/load/hpoa/_impl.py
- src/hpotk/annotations/load/hpoa/test__impl.py
- src/hpotk/annotations/test__base.py
- src/hpotk/annotations/test__simple.py
- src/hpotk/graph/_api.py
- src/hpotk/graph/_csr_graph.py
- src/hpotk/graph/test__api.py
- src/hpotk/model/__init__.py
- src/hpotk/model/_base.py
- src/hpotk/ontology/_default.py
- src/hpotk/validate/_hpo.py
- src/hpotk/validate/_model.py
- src/hpotk/validate/_util.py
- tests/algorithm/test_traversal.py
- tests/annotations/load/test_hpoa.py
- tests/test_validate.py
The `hpo-toolkit` data model now includes new members to model observation status:
- `hpotk.model.ObservableFeature` - for annotations that can be present or excluded
- `hpotk.model.FrequencyAwareFeature` - for annotations derived from a cohort of items that include the *n/m* info (numerator and denominator). A child of `ObservableFeature`
> Implement observation status for annotations

- src/hpotk/graph/_api.py
- src/hpotk/graph/_csr_graph.py
- src/hpotk/graph/test__api.py
- src/hpotk/graph/test__csr_graph.py
Raise `ValueError` if the query `TermId` is not present in the graph.
> Graph traversals fail if the query node does not exist in the graph

- src/hpotk/model/_term_id.py
- src/hpotk/model/test__term_id.py
- src/hpotk/ontology/load/obographs/_load.py
- src/hpotk/util.py
Cache the `TermId`'s hash by default to improve performance of hash-dependent operations.
> Cache the hash of the `TermId`

- src/hpotk/graph/_factory.py
- src/hpotk/model/_term.py
- src/hpotk/model/_term_id.py
- src/hpotk/ontology/_default.py
- tests/ontology/load/test_obographs.py
- tests/test_obographs.py
- tests/test_term_id.py
Add type checks to terms and ontology objects.
> Add type checks to terms, and ontology

- pyproject.toml
``np.fromiter`` only supports ``dtype=object`` from version ``1.23.0`` on (see https://numpy.org/doc/stable/reference/generated/numpy.fromiter.html). Without this requirement, an error is thrown when using ``hpotk.ontology.load.obographs.load_minimal_ontology(hpo_url)`` : ``ValueError: cannot create object arrays from iterator``
> Require `numpy~=1.23.0` to support creating object arrays from iterables.

- docs/use-hierarchy.rst
- src/hpotk/graph/_api.py
- src/hpotk/graph/_test__api.py
Correct the type annotations on `OntologyGraph.get_children`, `OntologyGraph.get_parents`, `OntologyGraph.get_ancestors`, `OntologyGraph.get_descendants`.
Previously, we promised *iterable*s while the methods in fact provide *iterator*s. This may have led to a bug if the iterator was used, e.g. within a nested loop:
```python
hpo: MinimalOntology = ...
parents = hpo.graph.get_parents('HP:0001250')
for _ in range(5):
for parent in parents:
print(parent)
```
The loop above would, in fact, print only during the first iteration of the outer loop, and the iterator would be "consumed" for the remaining 4 iterations.
> Fix `OntologyGraph` type annotations - breaking change

- src/hpotk/model/__init__.py
- src/hpotk/model/_base.py
- src/hpotk/ontology/_api.py
- src/hpotk/ontology/_default.py
Add convenience method for getting term name:
```python
hpo: MinimalOntology = ...
hpo.get_term_name('HP:0001250')
```
prints `Seizure`
> Add convenience method for getting term name

- src/hpotk/graph/_api.py
- src/hpotk/graph/_test__api.py
- src/hpotk/graph/_test_data.py
Implement function to compute the edge distance between two ontology graph nodes.
> Implement edge distance on `OntologyGraph`.

- .github/workflows/python_ci.yml
- benches/graph_traversal.py
- docs/setup.rst
- docs/user-guide/use-hierarchy.rst
- pyproject.toml
- src/hpotk/graph/__init__.py
- src/hpotk/graph/_api.py
- src/hpotk/graph/_csr_idx_graph.py
- src/hpotk/graph/_factory.py
- src/hpotk/graph/_test__factory.py
- src/hpotk/graph/_test_csr_idx_graph.py
- src/hpotk/ontology/load/obographs/_load.py
- tests/algorithm/test_similarity.py
- tests/algorithm/test_traversal.py
- tests/annotations/load/test_hpoa.py
- tests/conftest.py
- tests/ontology/load/test_obographs.py
- tests/test_obographs.py
- tests/test_validate.py
Add support for working with term ID indices, simplify the CSR data structures. 
Use `IndexedOntologyGraph` and `CsrIndexedGraphFactory` as default in `hpotk.load_ontology` and `hpotk.load_minimal_ontology`.
> Add `IndexedOntologyGraph`

- .gitignore
- HOW_TO_RELEASE.md
- benches/graph_traversal.py
- recipe/meta.yaml
- src/hpotk/__init__.py
> Release v0.4.2

- src/hpotk/graph/_api.py
- src/hpotk/graph/_test__api.py
Fix bug in `is_leaf` of `IndexedOntologyGraph` that produced the opposite results.
> Fix bug in `IndexedOntologyGraph.is_leaf`.

- docs/user-guide/load-ontology.rst
- src/hpotk/model/__init__.py
- src/hpotk/model/_term.py
- src/hpotk/ontology/load/obographs/_factory.py
- tests/ontology/load/test_obographs.py
- tests/test_obographs.py
- tests/test_term.py
Wrap *definition* into a `Definition` class, and add cross-references.
@pnrobinson, the cross-references of a definition can be obtained as:
```python
import hpotk
hpo: hpotk.MinimalOntology = ... # Get it from somewhere
term = hpotk.get_term('HP:0001626')  # Abnormality of the cardiovascular system
assert term.definition.definition == 'Any abnormality of the cardiovascular system.'
assert term.definition.xrefs == ('HPO:probinson',)
```
closes #61
> Add definition cross-references

- README.md
- docs/user-guide/index.rst
- docs/user-guide/load-ontology.rst
- docs/user-guide/use-ontology.rst
- src/hpotk/__init__.py
- src/hpotk/util/__init__.py
- src/hpotk/util/store/__init__.py
- src/hpotk/util/store/_api.py
- src/hpotk/util/store/_config.py
- src/hpotk/util/store/_github.py
- tests/test_store.py
Adding the `OntologyStore` API for local caching of the ontology releases.
Closes #7
> Add `OntologyStore` API

- src/hpotk/util/_log.py
Add optional `stream` argument to the `hpotk.util.setup_logging` function to support providing custom `typing.TextIO` to log the messages into.
> Support providing custom stream to the logger

- README.md
- docs/index.rst
- docs/setup.rst
- pyproject.toml
Update all URLs to point to the new `hpo-toolkit` location.
> Update urls after the repo move

- src/hpotk/store/__init__.py
- src/hpotk/store/_api.py
- src/hpotk/store/_config.py
- src/hpotk/store/_github.py
- tests/conftest.py
- tests/test_store.py
Fix `OntologyStore` bug where an ontology name can be constructed from `None` if release is not set.
> Prevent storing ontology file at path with `None` in name

- .gitignore
- docs/user-guide/load-ontology.rst
- src/hpotk/store/__init__.py
- src/hpotk/store/_api.py
- tests/test_store.py
Expose paths of ontology resources managed by the `OntologyStore`.
> Expose `OntologyStore` resource path and enable resource cleanup

- .editorconfig
- .flake8
- src/hpotk/__init__.py
- src/hpotk/ontology/load/obographs/_load.py
- tests/test_term_id.py
Test that different `TermId` formats hash properly.
Reformat parametrized tests to improve readability.
> Test `TermId` hashing, add editor config and linter config

- src/hpotk/__init__.py
The ontology loaders should stay in the top-level package.
> Reexport ontology loaders

- src/hpotk/store/_api.py
- src/hpotk/store/_config.py
- src/hpotk/store/_github.py
- tests/test_store.py
Only include the ontology release tags that match `^v\d{4}-\d{2}-\d{2}$` pattern.
> Improve ontology release tag handling

- src/hpotk/store/_api.py
- src/hpotk/store/_github.py
- tests/test_store.py
The ontology store will now accept release tags without `v` prefix (e.g. `2025-03-03` instead of `v2025-03-03`).
> Be more flexible with HPO tags

- src/hpotk/constants/__init__.py
- src/hpotk/constants/hpo/__init__.py
- src/hpotk/constants/hpo/frequency.py
- src/hpotk/graph/_api.py
- src/hpotk/graph/_factory.py
- src/hpotk/graph/_test__api.py
- src/hpotk/ontology/__init__.py
- src/hpotk/ontology/_api.py
- src/hpotk/ontology/_default.py
- src/hpotk/ontology/load/__init__.py
- tests/test_constants.py
Add support for hierarchy queries that test if a term is equal to or parent/ancestor/child/descendant of another term.
Fix a bunch of lints.
> Add hierarchy queries that include the source
